--- 
title: "Appunti di Costruzione e validazione di strumenti di misura dell'efficacia dell'intervento psicologico in neuropsicologia -- B020881 (B213)"
author: "Corrado Caudek"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [refs.bib, book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
colorlinks: yes
graphics: yes
lot: yes
lof: yes
monofont: "MesloLGS NF"
monofontoptions: "Scale=0.775"
description: "This document contains the materials of the lessons of Costruzione e validazione di strumenti di misura dell'efficacia dell'intervento psicologico in neuropsicologia -- B020881 (B213) (2022/2023) aimed at students of the second year of the Degree Course Laurea Magistrale in Psicologia (LM-51) of the University of Florence, Italy."
github-repo: ccaudek/cfa_book
---

# Benvenuti {-}

Benvenuti nella versione online di *Costruzione e validazione di strumenti di misura dell'efficacia dell'intervento psicologico in neuropsicologia*. Questo sito web contiene il materiale didattico dell'insegnamento B020881 (B213) rivolto agli studenti del secondo anno del Corso di Laurea Magistrale in Psicologia Clinica e della Salute e Neuropsicologia (curriculum: assessment e intervento psicologici in neuropsicologia - E21), A.A. 2022-2023. L'insegnamento si propone di fornire agli studenti un'introduzione all'assessment psicologico, ovvero un insieme di  conoscenze/competenze che si pongono all'intersezione tra psicometria, statistica e informatica.

L'obiettivo dell'insegnamento sarà concentrato sull'analisi fattoriale esplorativa (EFA) e sulla confermatoria (CFA), che sono gli strumenti principali utilizzati nel processo di sviluppo dei test psicometrici per esaminare la struttura latente di una scala psicologica, ad esempio un questionario. In particolare, la CFA viene utilizzata per determinare il numero di dimensioni sottostanti gli indicatori (fattori) e l'intensità delle relazioni tra gli indicatori e i fattori (saturazioni fattoriali). La CFA è anche utile per comprendere come effettuare lo scoring dei test e per identificare il numero di sottoscale e come queste debbano essere codificate.

Inoltre, la CFA è un importante strumento analitico nella valutazione psicometrica, in quanto consente di stimare l'affidabilità della scala dei test psicometrici, evitando i problemi della teoria classica dei test, ad esempio l'alpha di Cronbach. Con i recenti progressi nell'analisi dei dati categoriali, la CFA offre ora un quadro analitico comparabile a quello offerto dalla teoria di risposta agli item (IRT). In realtà, secondo @brown2015confirmatory, la CFA offre una maggiore flessibilità analitica rispetto al tradizionale modello IRT.

In psicologia, un costrutto è un concetto teorico che può essere operazionalizzato attraverso un insieme di indicatori o fattori. Ad esempio, i disturbi mentali sono costrutti manifestati da sintomi che possono essere riportati dal paziente o osservati da altri. La CFA è uno strumento analitico fondamentale per la validazione dei costrutti psicologici, in quanto consente di valutare la validità convergente e discriminante dei fattori teorici. La validità convergente viene indicata dall'evidenza di correlazioni significative tra diversi indicatori di costrutti simili o sovrapposti, mentre la validità discriminante viene indicata da correlazioni basse o nulle tra indicatori di costrutti teoricamente distinti. La CFA ha il vantaggio di correggere l'errore di misurazione nei modelli tradizionali, fornendo stime corrette di validità convergente e discriminante.

Spesso, la covarianza tra le misure osservate è dovuta a fonti di varianza diverse dai fattori di interesse, come gli effetti del metodo utilizzato per la misurazione. Questi effetti del metodo possono produrre risultati fuorvianti se non vengono correttamente gestiti. Ad esempio, i questionari che contengono elementi formulati positivamente e negativamente possono presentare effetti del metodo che influenzano la covarianza tra gli indicatori. L'EFA non è in grado di stimare gli effetti del metodo e può quindi produrre risultati fuorvianti. Al contrario, la CFA consente di specificare gli effetti del metodo come parte del modello di misurazione, fornendo un quadro analitico migliore rispetto ai metodi tradizionali che non tengono conto dell'errore di misurazione.

La CFA ha un'altra importante capacità: affrontare il problema della generalizzabilità del modello di misurazione tra gruppi di individui o nel tempo. Per garantire che un test sia affidabile e valido per una popolazione eterogenea, è necessario stabilire che le sue proprietà di misurazione siano equivalenti tra i sottogruppi della popolazione, come sesso o razza. Tuttavia, se alcuni degli elementi del test non misurano il costrutto sottostante in modo comparabile tra gruppi, si dice che il test sia distorto, e ciò può produrre stime fuorvianti. La CFA affronta questo problema esaminando gruppi multipli mediante modelli MIMIC, che permettono di valutare se il modello di misurazione è equivalente tra gruppi. Questo tipo di analisi può anche essere applicato per esaminare l'invarianza della misurazione longitudinale, ovvero per valutare se il cambiamento nel tempo sia dovuto a un vero cambiamento dei rispondenti o a cambiamenti nel modo di rispondere alla scala nel tempo.

Prima di parlare delle tecniche della CFA, è importante introdurre la EFA e la teoria classica dei test. La EFA viene spesso utilizzata nei primi passi dello sviluppo di una scala psicometrica, mentre la teoria classica dei test fornisce la base teorica di partenza, a cui la CFA e i modelli di equazioni strutturali si sviluppano successivamente.

Nel corso, si presta particolare attenzione non solo alla comprensione dei concetti teorici essenziali per la costruzione e la validazione di uno strumento di misura in psicologia, ma anche alla capacità di applicare tali concetti in situazioni concrete. Pertanto, durante la trattazione dei concetti teorici, verranno presentate anche applicazioni pratiche. Per effettuare tali applicazioni, sarà necessario utilizzare un software. In questo insegnamento useremo $\textsf{R}$ [@rmanual] quale linguaggio di programmazione probabilistica e, tra gli altri, il pacchetto `lavaan` che consente di svolgere le analisi statistiche della CFA e della EFA [@beaujean2014latent]. La teoria classica dei test verrà descritta con riferimento al classico testo di @lord1968statistical. Questa dispensa, inoltre, segue da vicino la trattazione della CFA fornita nei testi di @mcdonald2013test e di @brown2015confirmatory.

Trattando di argomenti avanzati, questo insegnamento presuppone la conoscenza di base dei concetti fondamentali della teoria delle probabilità; presuppone inoltre il possesso delle conoscenze di base necessarie per procedere all'utilizzo di $\textsf{R}$. Un'introduzione a $\textsf{R}$ è fornita nella prima parte della dispensa.

```{block2, type='flushright', html.tag='p'}
Corrado Caudek  
Marzo 2023
```


## License {-}

The online version of this book is licensed under the [Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License](https://creativecommons.org/licenses/by-nc-nd/4.0/).

The code is public domain, licensed under [Creative Commons CC0 1.0 Universal (CC0 1.0)](https://creativecommons.org/publicdomain/zero/1.0/).



